#spring:
#  datasource:
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
#  jpa:
#    open-in-view: true
#    hibernate:
#
#      ddl-auto: create
#spring:
#  datasource:
#    url: ${DATABASE_URL}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create

#spring:
#  datasource:
#    url: jdbc:postgresql://postgres:OSBxyyFFQVKbobTUKOmNweDAoLNpsGaC@postgres.railway.internal:5432/railway
#    username: postgres
#    password: OSBxyyFFQVKbobTUKOmNweDAoLNpsGaC
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create
#

